name: DevilsWhistleDetector
dependencies:
  - python=3.8
  - tensorflow-gpu=2.6
  - keras=2.6.*
  - numpy=1.23.*
  - ipykernel=6.15.*
  - pillow=9.2.*
  - scipy=1.10.*
  - pip=22.2.*
  - pip:
      - tensorflow-addons~=0.13.0
      - tensorflow-model-optimization==0.7.0
      - plotly~=5.15.0
      - kaleido~=0.2.1
      - pandas~=2.0.3
      - sounddevice~=0.4.6
      - pyflann-py3
      - tqdm>=4.41.0
      - scikit-learn~=1.2.1
      - imbalanced-learn~=0.10.1
